export enum BicepExercises {
  BARBELL_CURL= "Barbell Curl",
  BARBELL_PREACHER_CURL = "Barbell Preacher Curl",
  BAYESIAN_CURL = "Bayesian Curl",
  BODYWEIGHT_CURL = "Bodywegiht Curl",
  CABLE_CROSSOVER_BICEPCURL = "Cable Crossover Bicep Curl",
  CABLE_CURL_WITH_BAR = "Cable Curl With Bar",
  CABLE_CURL_WITH_ROPE = "Cable Curl With Rope",
  CONCENTRATION_CURL = "Concentration Curl",
  DRAG_CURL = "Drag Curl",
  DUMBBELL_CURL = "Dumbbell Curl",
  DUMBBELL_PREACHER_CURL = "Dumbbell Preacher Curl",
  HAMMER_CURL = "Hammer Curl",
  INCLINE_DUMBBELL_CURL = "Incline Dumbbell Curl",
  MACHINE_BICEP_CURL = "Machine Bicep Curl",
  RESISTANCE_BAND_CURL = "Resistance Band Curl ",
  SPIDER_CURL = "Spider Curl",
  ZOTTMAN_CURL = "Zottman Curl",
}
